apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-service
  namespace: adv-devops
spec:
  ports:
    - nodePort: 32272
      port: 15672
      protocol: TCP
      targetPort: 15672
      name: http
    - port: 5672
      protocol: TCP
      targetPort: 5672
      name: amqp
  selector:
    app: rabbitmq
  type: NodePort
