apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}-producer
  name: {{ .Values.name }}-producer
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-producer
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-producer
    spec:
      containers:
        - image: {{ .Values.image.repository }}/producer:<TAG>
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: producer
          tty: true
          command: ["python"]
          args: ["producer.py", "-p", "5672", "-s", "rabbitmq", "-m", '"Hello"', "-r", "30"]
